name: Build and Test .NET 8 Apps

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build solution
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test
